<%
director_uuid = 'CHANGE-ME'
deployment_name = 'jenkins'
%>
---
name: <%= deployment_name %>
director_uuid: <%= director_uuid %>

releases:
- name: jenkins-swarm
  version: latest
- name: docker
  version: latest

compilation:
  workers: 1
  network: default
  reuse_compilation_vms: true
  cloud_properties: {}

update:
  canaries: 0
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 32
  serial: false

networks:
- name: default
  type: manual
  subnets:
  - cloud_properties: {}
    range: 10.244.0.0/24
    reserved:
    - 10.244.0.1
    static:
    - 10.244.0.2

resource_pools:
- name: default
  network: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

jobs:
- name: jenkins-master
  templates:
  - name: jenkins
    release: jenkins-swarm
  instances: 1
  resource_pool: default
  persistent_disk: 65536
  networks:
  - name: default
    static_ips:
    - 10.244.0.2
  properties: {}

- name: jenkins-slave
  templates:
  - name: docker
    release: docker
  - name: swarm-agent
    release: jenkins-swarm
  instances: 1
  resource_pool: default
  networks:
  - name: default
  properties: {}

properties:
  docker:
    tcp_address: 0.0.0.0
  jenkins:
    master:
      url: http://10.244.0.2:8080
      num_executors: 0
      admin_user: admin
      admin_password: password
      slave_user: agent
      slave_password: password
    slave:
      num_executors: 6
